let head1 = document.getElementById('head1')
let head2 = document.getElementById('head2')
let head3 = document.getElementById('head3')
let head4 = document.getElementById('head4')
let head5 = document.getElementById('head5')
let head6 = document.getElementById('head6')

let listItems = document.getElementsByClassName('list-item')
let list = document.getElementById('list')
let list2 = document.getElementById('list2')

// console.log(head1.parentElement)
// console.log(head2.parentNode)
// console.log(head3.previousElementSibling)
// console.log(head3.previousElementSibling.previousElementSibling)
// console.log(head2.nextElementSibling)
// console.log(head2.nextElementSibling.nextElementSibling)

// console.log(listItems)
// console.log(listItems[2].nextSibling)
// console.log(listItems[2].nextSibling.nextSibling)
// console.log(listItems[2].nextSibling.nextSibling.nextSibling)
// console.log(listItems[2].previousElementSibling)

console.log(list)
console.log(list.children)
console.log(list.children[2])
console.log(list.childElementCount)
console.log(list.childNodes)
console.log(list.children[3].hasChildNodes())
console.log(list.children[3].childNodes)

console.log(list2.childElementCount)
console.log(list2.hasChildNodes())
console.log(list2.children[3].hasChildNodes())
console.log(list2.firstChild)
console.log(list2.lastChild)
console.log(list2.firstElementChild)
console.log(list2.lastElementChild)
