
import "./globals.css";
import Nav from "@/app/(components)/Nav";
import AuthProvider from "@/app/(components)/AuthProvider";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AuthProvider>
          <body className={"bg-gray-100"}>
          <Nav/>
          <main className={"m-2"}>
              {children}
          </main>
          </body>
      </AuthProvider>

    </html>
  );
}
